name: trcgg_py CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
    # STEP - ACCESS - TRC.GG Server
    - name: Connect to trc.gg Server
      run: |
        echo ${{ secrets.WAS_HOST }}
        echo ${{ secrets.WAS_USERNAME }}
        echo ${{ secrets.SSH_KEY }}
        echo ${{ secrets.WAS_SSH_PORT }}
