name: trcgg_py CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
    
    # STEP - CHECKOUT
    - name: Checkout source code
      uses: actions/checkout@v4
      
    # STEP - VARIABLE SETTING
    - name: Set Environment Variables and List Files
      run: |
        echo "DB_USERNAME=$DB_USERNAME" >> .env
        echo "DB_PASSWORD=$DB_PASSWORD" >> .env
        echo "DB_HOST=$DB_HOST" >> .env
        echo "DB_PORT=$DB_PORT" >> .env
        echo "DB_NAME=$DB_NAME" >> .env
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.WAS_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
    
