name: trcgg_py CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
    
    # STEP - VARIABLE SETTING
    - name: Setting Variables from .env
      run: |
        touch .env
        echo DB_USERNAME: ${{ secrets.DB_USERNAME }} >> .env
        echo DB_PASSWORD: ${{ secrets.DB_PASSWORD }} >> .env
        echo DB_HOST: ${{ secrets.WAS_HOST }} >> .env
        echo DB_PORT: ${{ secrets.DB_PORT }} >> .env
        echo DB_NAME: ${{ secrets.DB_NAME }} >> .env
        cat .env
        ls
    
    # STEP - CHECKOUT
    - name: Checkout source code
      uses: actions/checkout@v4

    # STEP - ACCESS - Docker Hub
    - name: Connect to Docker hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # STEP - BUILD&PUBLISH - Docker image
    - name: Build and Publishing the Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm64 \
        --tag codingpoppy94/trc_service:1.1 \
        --push .

    # STEP - ACCESS - TRC.GG Server
    - name: Connect to trc.gg Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.WAS_HOST }}
        username: ${{ secrets.WAS_USERNAME }}
        password: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.WAS_SSH_PORT }}
        script: |
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)
          docker pull codingpoppy94/trc_service:1.1
          docker pull codingpoppy94/trc_bot:1.0
          docker network create trc_network
          docker run -d --name trc_service -p 24001:24001 --network trc_network codingpoppy94/trc_service:1.1
          docker run -d --name trc_bot --network trc_network codingpoppy94/trc_bot:1.0
