name: trcgg_py CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: get IP
      id: ip
      uses: haythem/public-ip@v1.3

    - name: print IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}

            
